//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmscy_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class capsule
    {
        public int cap_id { get; set; }
        public string cap_Name { get; set; }
        public string output { get; set; }
        public string cap_Size { get; set; }
        public string machine_dimension { get; set; }
        public string shiping_weight { get; set; }
        public string Capsules_Image { get; set; }
    }
}
