//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmscy_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class career
    {
        public int id { get; set; }
        public string firsrt_name { get; set; }
        public string last_name { get; set; }
        public string gendre { get; set; }
        public string country { get; set; }
        public string address { get; set; }
        public Nullable<int> phone_no { get; set; }
        public string email { get; set; }
        public string Qualification { get; set; }
        public string Experience { get; set; }
        public string cover_letter { get; set; }
        public string resume { get; set; }
    }
}
