//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmscy_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Liquid_filling
    {
        public int Lq_Id { get; set; }
        public string lq_Name { get; set; }
        public string Air_Pressure { get; set; }
        public string Air_Volume { get; set; }
        public string Filling_Speed { get; set; }
        public string Filing_Range { get; set; }
        public string LQ_Image { get; set; }
    }
}
