//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmscy_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qoute_Us
    {
        public int Id { get; set; }
        public string Full_Name { get; set; }
        public string Company_Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Postal_Code { get; set; }
        public string Country { get; set; }
        public string Email { get; set; }
        public Nullable<int> Phone { get; set; }
        public string Comments { get; set; }
    }
}
