//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmscy_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tablet
    {
        public int TB_ID { get; set; }
        public string Tb_Name { get; set; }
        public string Model_No { get; set; }
        public string Dies { get; set; }
        public string Max_Pressure { get; set; }
        public string Max_Diametere { get; set; }
        public string Max_Depth { get; set; }
        public string Production_Capacity { get; set; }
        public string Machine_Size { get; set; }
        public string Net_Weight { get; set; }
        public string tablet_Image { get; set; }
    }
}
